apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: local-ai-data
type: Opaque
stringData:
  POSTGRES_DB: local_ai
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: +fnSToMl1XfBie8lP39P3eaivj/7q+NjIhLffV8Kq9g=
