apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: local-ai-n8n
  labels:
    app: n8n
data:
  # n8n configuration
  N8N_PORT: "5678"
  N8N_PROTOCOL: "https"
  N8N_LISTEN_ADDRESS: "0.0.0.0"

  # Database (PostgreSQL via Supabase)
  # Connection string should be in secret
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "postgres"

  # n8n SSL/TLS (handled by Ingress)
  N8N_TRUSTED_HEADER: "X-Forwarded-Proto"

  # Storage
  N8N_DEFAULT_LOCALE: "en"
  N8N_TIMEZONE: "UTC"

  # Webhook configuration
  WEBHOOK_URL: "https://n8n.lupulup.com/webhook"
  WEBHOOK_TUNNEL_URL: "https://n8n.lupulup.com/webhook"

  # Security
  N8N_SECURE_COOKIE: "true"
  COOKIE_SAMESITE: "Lax"

  # Logging
  LOG_LEVEL: "info"

  # Feature flags
  N8N_SKIP_WEBHOOK_VALIDATION_PAYLOAD_SIZE_CHECK: "false"

  # Prevent auto-signup
  N8N_USER_MANAGEMENT_DISABLED: "false"

  # External services integration
  # Ollama integration
  OLLAMA_BASE_URL: "https://ollama.mylegion5pro.me"

  # Open WebUI integration
  OPENWEBUI_BASE_URL: "https://openwebui.mylegion5pro.me"

  # Supabase/PostgreSQL
  DB_POSTGRESDB_HOST: "supabase-postgres.local-ai-data.svc.cluster.local"

  # Qdrant Vector DB
  QDRANT_URL: "http://qdrant.local-ai-data.svc.cluster.local:6333"

  # Neo4j
  NEO4J_URI: "bolt://neo4j.local-ai-data.svc.cluster.local:7687"

  # Redis for queues
  QUEUE_BULL_REDIS_HOST: "redis.local-ai-system.svc.cluster.local"
  QUEUE_BULL_REDIS_PORT: "6379"

  # Keycloak OIDC Configuration for n8n
  N8N_AUTH_EXCLUDEENDPOINTS: "/rest/oauth2/callback,/rest/webhook"
  N8N_EXTERNAL_FRONTEND_URL: "https://n8n.lupulup.com"
