apiVersion: v1
kind: Namespace
metadata:
  name: local-ai-search
  labels:
    app: searxng
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: local-ai-search
data:
  settings.yml: |
    # Minimal SearXNG settings for Kubernetes deployment
    server:
      port: 8080
      bind_address: "0.0.0.0"
      base_url: "https://searxng.lupulup.com/"
      image_proxy: true
      trusted_proxies:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
    result_proxy:
      url: ""
    redis:
      url: "redis://redis.local-ai-system.svc.cluster.local:6379/0"
    search:
      autocomplete: "duckduckgo"
    limiter:
      enabled: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-data
  namespace: local-ai-search
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: local-ai-search
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
      - name: searxng
        image: searxng/searxng:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: BASE_URL
          value: "https://searxng.lupulup.com/"
        - name: SEARXNG_REDIS_URL
          value: "redis://redis.local-ai-system.svc.cluster.local:6379"
        - name: PROXY_HTTP_X_FOR
          value: "X-Forwarded-For"
        - name: PROXY_HTTP_X_PROTO
          value: "X-Forwarded-Proto"
        - name: PROXY_HTTP_X_HOST
          value: "X-Forwarded-Host"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: searxng-data
        persistentVolumeClaim:
          claimName: searxng-data
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: searxng
  namespace: local-ai-search
spec:
  type: ClusterIP
  selector:
    app: searxng
  ports:
  - name: http
    port: 8080
    targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: searxng
  namespace: local-ai-search
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - searxng.lupulup.com
    secretName: searxng-tls
  rules:
  - host: searxng.lupulup.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: searxng
            port:
              number: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: searxng-tls
  namespace: local-ai-search
spec:
  secretName: searxng-tls
  duration: 2160h
  renewBefore: 360h
  commonName: searxng.lupulup.com
  dnsNames:
  - searxng.lupulup.com
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
