apiVersion: v1
kind: Secret
metadata:
  name: flowise-secrets
  namespace: local-ai-flowise
type: Opaque
stringData:
  FLOWISE_PASSWORD: 4LgLzOwfhmbOawV/ytVF+g==
  FLOWISE_APIKEY: tAx6Hi4H+92gT7mgfRvutHWXcRjVzdpUdslfK5j5BKk=
